/* ============================================================================
   SF KNOWLEDGE HUB — Python for Robot Framework — CERTIFICATION QUESTION BANK
   Exposes window.QUESTION_BANK consumed by certification-test.html.
   Each question: { id, stem, options:{A,B,C,D}, correct:'A'|'B'|'C'|'D' }.
   24 questions (6 per module); the exam samples 20 at random per attempt.
   ============================================================================ */
window.QUESTION_BANK = [
  { id:"m1q1", stem:"Which command installs Robot Framework and provides the \"robot\" command?",
    options:{A:"pip install robotframework", B:"robot --install", C:"python -m robot install", D:"npm install robotframework"}, correct:"A" },
  { id:"m1q2", stem:"Which three section headers appear in a typical .robot file?",
    options:{A:"Imports, Steps, Checks", B:"Settings, Test Cases, Keywords", C:"Config, Tests, Methods", D:"Setup, Body, Teardown"}, correct:"B" },
  { id:"m1q3", stem:"A Python function named add_numbers in an imported library is called from a test as which keyword?",
    options:{A:"add_numbers", B:"AddNumbers", C:"Add Numbers", D:"add-numbers"}, correct:"C" },
  { id:"m1q4", stem:"How does Robot Framework separate a keyword from its arguments on a line?",
    options:{A:"A comma", B:"A single space", C:"A semicolon", D:"Two or more spaces"}, correct:"D" },
  { id:"m1q5", stem:"After a run, which file shows each keyword’s step-by-step status?",
    options:{A:"log.html", B:"output.xml", C:"report.txt", D:"settings.robot"}, correct:"A" },
  { id:"m1q6", stem:"Which setting imports a Python library file into a .robot suite?",
    options:{A:"Import   MyLib.py", B:"Library   MyLib.py", C:"Use   MyLib.py", D:"Resource   MyLib.py"}, correct:"B" },
  { id:"m2q1", stem:"A keyword function returns a float. What does the test receive when it captures the result?",
    options:{A:"Nothing", B:"Always a string", C:"A float value", D:"An integer only"}, correct:"C" },
  { id:"m2q2", stem:"In def apply_discount(price, percent=0):, what is true of percent?",
    options:{A:"It is required", B:"It cannot be a number", C:"It must be passed positionally only", D:"It is optional and defaults to 0"}, correct:"D" },
  { id:"m2q3", stem:"Why do keyword functions often call int() or float() on their arguments?",
    options:{A:"Robot passes arguments as strings, so they need conversion before arithmetic", B:"Python cannot store numbers otherwise", C:"It is only for negatives", D:"To make them run faster"}, correct:"A" },
  { id:"m2q4", stem:"Which operator tests two values for equality?",
    options:{A:"=", B:"==", C:"=>", D:":="}, correct:"B" },
  { id:"m2q5", stem:"In \"for price in prices:\", what is price on each pass?",
    options:{A:"The whole list", B:"The list length", C:"One item from prices, in turn", D:"The index only"}, correct:"C" },
  { id:"m2q6", stem:"How can a test pass an argument to a keyword by name?",
    options:{A:"Only via a variable file", B:"Names are not allowed", C:"By wrapping it in quotes", D:"Using name=value syntax, e.g. percent=10"}, correct:"D" },
  { id:"m3q1", stem:"In a Python list \"items\", which expression gives the first element?",
    options:{A:"items[0]", B:"items[1]", C:"items.first()", D:"items(0)"}, correct:"A" },
  { id:"m3q2", stem:"Why use record.get(\"active\", False) instead of record[\"active\"]?",
    options:{A:"It is always faster", B:"It returns a default instead of raising an error when the key is missing", C:"Bracket access fails on dicts", D:"get() sorts the dictionary"}, correct:"B" },
  { id:"m3q3", stem:"What does \"Asha,active\\n\".strip().split(\",\") produce?",
    options:{A:"[\"Asha,active\"]", B:"\"Asha,active\"", C:"[\"Asha\", \"active\"]", D:"An error"}, correct:"C" },
  { id:"m3q4", stem:"What happens when a keyword’s Python hits an unhandled raise ValueError(...)?",
    options:{A:"The suite is skipped", B:"It returns None silently", C:"Robot ignores it and passes", D:"The test step fails, with the message in the log"}, correct:"D" },
  { id:"m3q5", stem:"Which Robot keyword asserts that a keyword fails with an expected message?",
    options:{A:"Run Keyword And Expect Error", B:"Should Be Equal", C:"Length Should Be", D:"Should Contain"}, correct:"A" },
  { id:"m3q6", stem:"Which built-in keyword builds a Robot list to pass into a keyword?",
    options:{A:"Make Array", B:"Create List", C:"New List", D:"List Of"}, correct:"B" },
  { id:"m4q1", stem:"What does ROBOT_LIBRARY_SCOPE = \"SUITE\" mean for a library class?",
    options:{A:"It limits the library to one test", B:"A new instance per keyword call", C:"One shared instance across the suite, so state persists between tests", D:"It disables the library"}, correct:"C" },
  { id:"m4q2", stem:"With @keyword(\"Apply Coupon Code\") above def apply_coupon(...), what name do tests use?",
    options:{A:"apply_coupon", B:"applyCoupon", C:"Apply_Coupon", D:"Apply Coupon Code"}, correct:"D" },
  { id:"m4q3", stem:"Which setting pulls shared keywords from another file into a suite?",
    options:{A:"Resource", B:"Suite Teardown", C:"Variables", D:"Metadata"}, correct:"A" },
  { id:"m4q4", stem:"Why prefer an explicit wait keyword over a fixed Sleep?",
    options:{A:"Sleep is not valid", B:"A wait proceeds as soon as the condition is met; a sleep always costs the full delay", C:"Waits only work in browsers", D:"Sleep cannot take a number"}, correct:"B" },
  { id:"m4q5", stem:"In a suite using both SeleniumLibrary and your CartLibrary, where does Open Browser come from?",
    options:{A:"Your CartLibrary", B:"Robot built-ins", C:"SeleniumLibrary", D:"The Resource file"}, correct:"C" },
  { id:"m4q6", stem:"Which import brings in the logger used to write messages to the test log?",
    options:{A:"from selenium import logger", B:"import logging as logger", C:"from robot import log", D:"from robot.api import logger"}, correct:"D" }
];
